---
- name: Setup prerequisite variables
  hosts: localhost
  gather_facts: True
  tasks:
    - include_tasks: keypair.yml

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  tasks:
    - include_tasks: vpc.yml
    - include_tasks: launch.yml
      with_items:
        - openshift-master
        - openshift-node-1
        - openshift-node-2
        - openshift-node-3
      loop_control:
        loop_var: node_name
