# vim: set ft=ansible tabstop=2 shiftwidth=2 :
---
- name: Setup prerequisite variables
  hosts: localhost
  gather_facts: True
  tasks:
    - include_tasks: keypair.yml

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Initialize empty list for provisioned virtual machines
      set_fact:
        provisioned_vms: []

    # create our virtual private cloud and networks
    - include_tasks: vpc.yml

    # setup security groups
    - include_tasks: security_groups.yml
      with_items: "{{ openshift_security_groups }}"
      loop_control:
        loop_var: group

    # launch virtual machines
    - include_tasks: launch.yml
      with_items: "{{ openshift_nodes }}"
      loop_control:
        loop_var: node
